# Generated by Django 4.1 on 2022-08-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarymodel',
            name='days_of_the_week',
        ),
        migrations.AddField(
            model_name='diarymodel',
            name='day_of_the_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='diarymodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diarymodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
