# Generated by Django 4.1 on 2022-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diarymodel_days_of_the_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymodel',
            name='header',
            field=models.CharField(default='', max_length=55),
        ),
    ]
