# Generated by Django 4.1 on 2022-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diarymodel_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymodel',
            name='header',
            field=models.CharField(default='', max_length=65),
        ),
    ]
